FROM node:25-alpine3.22

WORKDIR /app

# Install the requirements
# three.js, vite, ws, etc.
COPY ./package.json ./package-lock.json ./dist/ .

RUN npm install

EXPOSE 5173
#EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
